name: 'Get & cache dependencies'
description: 'Get the dependencies via npm and cache them'
inputs:
  caching:
    description: 'whether to enable cache'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache is used'
    value:  ${{ steps.install.name }}
runs:
  using: 'composite'
  steps:
    - name: cache dependencies
      id: cache
      if:  inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "name=${{inputs.caching}}" >> "$GITHUB_OUTPUT"
      shell: bash