# name: matrics demo
# on: push
# jobs:
#   build:
#     continue-on-error: true
#     strategy:
#       matrix:
#         node-version: [12, 14, 16]
#         operation-system: [ubuntu-latest,windows-latest]
#         include:
#           - node-version: 18
#             operation-system: ubuntu-latest
#         exclude:
#           - node-version: 12
#             operation-system: windows-latest
#     runs-on: ${{matrix.operation-system}}
#     steps:
#       - name: get code
#         uses: actions/checkout@v3
#       - name:  install nodejs
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: install dependenies
#         run: npm ci
#       - name: build project
#         run: npm run build