name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        type: string
        default: dist
    outputs:
      result: 
        description: export result
        value: ${{jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.export.outputs.outcome }}
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with: 
          name: ${{inputs.artifact-name}}
      - name: list files
        run: ls 
      - name: output information
        run: echo "deploying"
      - name: export outputs
        id: export
        run: echo "outcome=success" > $GITHUB_OUTPUT