name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        type: string
        default: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with: 
          name: ${{inputs.artifact-name}}
      - name: list files
        run: ls 
      - name: output information
        run: echo "deploying"